/**
 * Last updated: 2023-03-15
 *
 * Author(s):
 * Ghazaldeep Kaur <kaur0762@algonquinlive.com>
 * Verity Stevens <stev0298@algonquinlive.com>
 * Justin Bernard <bern0241@algonquinlive.com>
 */

import React, { useState, useEffect } from 'react';
import Head from 'next/head';
 import Layout from '@/components/common/Layout';
 import styles from '@/styles/Home.module.css';
 import { useUser } from '@/context/userContext';
 import { useRouter } from 'next/router';
 
 // Components
 import SignOutButton from '@/components/common/SignOutButton';
 
 export default function Home() {
     const [user, setUser, authRoles, setAuthRoles] = useUser();
     const router = useRouter();
     return (
         <>
             <Head>
                 <title>Ottawa Rec Sports</title>
                 <meta name="description" content="Generated by create next app" />
                 <meta name="viewport" content="width=device-width, initial-scale=1" />
                 <link rel="icon" href="/images/ORS-Logo.png" />
             </Head>
 
             <main className={styles.main}>
                 <div className="flex flex-col">
                     <h1>Sports Page</h1>
                 </div>
             </main>
         </>
     );
 }
 