/**
 * Last updated: 2023-03-29
 *
 * Author(s):
 * Ghazaldeep Kaur <kaur0762@algonquinlive.com>
 * Verity Stevens <stev0298@algonquinlive.com>
 * Justin Bernard <bern0241@algonquinlive.com>
 */

import React, { useState, useEffect } from 'react';
import Head from 'next/head';
 import Layout from '@/components/common/Layout';
 import styles from '@/styles/Home.module.css';
 import { useUser } from '@/context/userContext';
 import { useRouter } from 'next/router';
 
 // Components
 import SignOutButton from '@/components/common/SignOutButton';
 // Tables
import LeagueTable from '@/components/sports/LeagueTable';
import SeasonTable from '@/components/sports/SeasonTable'; 
import DivisionTable from '@/components/sports/DivisionTable';

 export default function Home() {
     const [user, setUser, authRoles, setAuthRoles] = useUser();
     const router = useRouter();

    const [selectedLeague, setSelectedLeague] = useState(null);
    const [selectedSeason, setSelectedSeason] = useState(null);
    const [selectedDivision, setSelectedDivision] = useState(null);

     return (
         <>
             <Head>
                 <title>Ottawa Rec Sports</title>
                 <meta name="description" content="Generated by create next app" />
                 <meta name="viewport" content="width=device-width, initial-scale=1" />
                 <link rel="icon" href="/images/ORS-Logo.png" />
             </Head>
 
             <main className='w-full flex justify-center max-w-[70em] mx-auto'>
                 <div className="flex flex-col w-full">

                     <LeagueTable sport='Soccer' 
                                selectedLeague={selectedLeague} 
                                setSelectedLeague={setSelectedLeague} />
                     <SeasonTable selectedLeague={selectedLeague}
                                selectedSeason={selectedSeason} 
                                setSelectedSeason={setSelectedSeason} />
                     <DivisionTable selectedSeason={selectedSeason}
                        selectedDivision={selectedDivision} 
                        setSelectedDivision={setSelectedDivision} 
                        selectedLeague={selectedLeague} /> 
                 </div>
             </main>
         </>
     );
 }
 