/**
 * Last updated: 2023-04-11
 *
 * Author(s):
 * Ghazaldeep Kaur <kaur0762@algonquinlive.com>
 * Justin Bernard <bern0241@algonquinlive.com>
 */

import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import { useUser } from '@/context/userContext';
// Tables
import ACPLeagueTable from '@/components/admin-portal/leagues/LeagueTable';
import ACPSeasonTable from '@/components/admin-portal/leagues/SeasonTable';
import ACPDivisionTable from '@/components/admin-portal/leagues/DivisionTable';

  export default function ACPLeaguesPage() {
      const [user, setUser, authRoles, setAuthRoles] = useUser();

    const [selectedLeague, setSelectedLeague] = useState(null);
    const [selectedSeason, setSelectedSeason] = useState(null);
    const [selectedDivision, setSelectedDivision] = useState(null);
    const [leagues, setLeagues] = useState([]);

    if (!user || (!authRoles.includes('Admin') && !authRoles.includes('Owner'))) {
        return (
            <div className="flex items-center justify-center h-[50vh]">
                <h2>You do not have access for this page</h2>
            </div>
        );
    }

      return (
          <>
              <Head>
                  <title>Ottawa Rec Sports - Leagues</title>
                  <meta name="description" content="Generated by create next app" />
                  <meta name="viewport" content="width=device-width, initial-scale=1" />
                  <link rel="icon" href="/images/ORS-Logo.png" />
              </Head>
  
              <main className='w-full flex justify-center max-w-[70em] mx-auto'>
                  <div className="flex flex-col w-full">
                    <ACPLeagueTable sport='NotApplicable' 
                                selectedLeague={selectedLeague} 
                                setSelectedLeague={setSelectedLeague}
                                leagues={leagues} 
                                setLeagues={setLeagues} />
                    {leagues.length !== 0 && (
                        <>
                        <ACPSeasonTable selectedLeague={selectedLeague}
                                    selectedSeason={selectedSeason} 
                                    setSelectedSeason={setSelectedSeason} />
                        <ACPDivisionTable selectedSeason={selectedSeason}
                            selectedDivision={selectedDivision} 
                            setSelectedDivision={setSelectedDivision} 
                            selectedLeague={selectedLeague} 
                            />
                        </> 
                    )}
                  </div>
              </main>
          </>
      );
  }
  