import React from 'react';
import Head from 'next/head';

const OtherSports = () => {
	return (
		<>
			<Head>
				<title>Ottawa Rec Sports</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/images/ORS-Logo.png" />
			</Head>
			<main className="flex flex-col justify-center items-center w-full">
				<h1 className="text-xl sm:text-2xl">Sport Not Available.</h1>
				<p>Please check back again on a later time.</p>
			</main>
		</>
	);
};

export default OtherSports;
