/**
 * Last updated: 2023-04-03
 *
 * Author(s):
 * Verity Stevens <stev0298@algonquinlive.com>
 * Justin Bernard <bern0241@algonquinlive.com>
 * Ghazaldeep Kaur <kaur0762@algonquinlive.com>
 */

import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { API } from 'aws-amplify';
import { useRouter } from 'next/router';
import { Button } from 'flowbite-react';
import { IconChevronLeft } from '@tabler/icons-react';
import { IconArrowNarrowRight } from '@tabler/icons-react';
import Link from 'next/link';
import AWS from 'aws-sdk';
import Image from 'next/image';
import { getTeam, getImageFromS3, getPlayersByUsername } from '@/utils/graphql.services';
import { listPlayers, getTeam as getTeamQuery, getDivision, getSeason, getLeague } from '@/src/graphql/queries';

export default function PlayerProfile() {
	const [user, setUser] = useState(); // Cognito User
	const [profileImage, setProfileImage] = useState('');
	const [sport, setSport] = useState('Soccer');
	const [players, setPlayers] = useState(); // Player Table
	const [teams, setTeams] = useState([]);
	const router = useRouter();
	const userId = router.query.id;
	var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();

	useEffect(() => {
		if (!userId) {
			return;
		}
		const callMe = async () => {
			await fetchPlayerCognito();
			// await fetchPlayers();
			await fetchTeams();
		}
		callMe();
	}, [userId]);

	useEffect(() => {
		if (!user) {
			return;
		}
		getPicture();
	}, [user]);

	// useEffect(() =>{
	// 	if(player != undefined){
	// 		getTeamName();
	// 	}
	// }, [player]);

	const fetchPlayerCognito = async () => {
		var params = {
			UserPoolId: 'us-east-1_70GCK7G6t',
			Username: userId,
		};
		cognitoidentityserviceprovider.adminGetUser(params, function (err, data) {
			if (err) console.log(err, err.stack); // an error occurred
			// successful response
			else setUser(data);
		});
	};

	// GETS ALL PLAYER DATA MODELS FOR THIS USER (Every team they are in)
	// const fetchPlayers = async () => {
	// 	const data = await getPlayersByUsername(userId);
	// 	if (data) {
	// 		setPlayer(data);
	// 	}
	// };


	const getPicture = async () => {
		if (
			user.UserAttributes.find((o) => o.Name === 'picture')['Value'] === 'none'
		) {
			setProfileImage(null);
		} else {
			const url = await getImageFromS3(
				user.UserAttributes.find((o) => o.Name === 'picture')['Value']
			);
			setProfileImage(url);
		}
	};

	// const getTeamName = async () => {
	// 	if (player.soccer_stats){
	// 		const teamId = player.soccer_stats[0].team;
	// 	const data = await getTeam(teamId);
	// 	setTeamName(data.name);
	// 	}
	// 		else {
	// 	}
	// }

	const fetchTeams = async () => {
		setTeams([]);
		const variables = {
			filter: {
			  user_id: {
				eq: userId
			  },
			  teamID: {
				attributeExists: true
			  }
			}
		  };
		const players = await API.graphql({ 
			query: listPlayers, variables: variables
		});
		// console.log('PLAYERS??', players.data.listPlayers.items);
		if (!players) { return; }

		players.data.listPlayers.items.map(async (player) => {
			const apiData = await API.graphql({ query: getTeamQuery, variables: { id: player.teamID }});
			let data = await apiData.data.getTeam;
			console.log('data', data);
			if (data !== null) {
				data.player_role = player.role;
			}
			setTeams((teams) => 
			{
				return uniqueById([...teams, data])
			});
			console.log('TEAMS!', data)
			console.log('PLAYERS!', players.data.listPlayers.items)
		  })
	}

	// const getSportFromLeague = async (teamObj) => {
	// 	//Start with Team -> Division
	// 	const apiDataDivision = await API.graphql({ query: getDivision, variables: { id: '087b8643-5cef-4078-8b98-34c2e08ff737'}})
	// 	const dataDivision = await apiDataDivision.data.getDivision;
	// 	console.log('DATA DIVISION ID',apiDataDivision.data.getDivision.Teams.items.map(item => item.divisionId));
	// 	// Get Season from division
	// 	const apiDataSeason = await API.graphql({ query: getSeason, variables: { id: dataDivision.season }})
	// 	const dataSeason = await apiDataSeason.data.getSeason;
	// 	// Get League from season
	// 	const apiDataLeague = await API.graphql({ query: getLeague, variables: { id: dataSeason.league }})
	// 	const dataLeague = await apiDataLeague.data.getLeague;
	// 	setSport(dataLeague.sport);
	// } 

	function uniqueById(items) {
		const set = new Set();
		return items.filter((item) => {
			const isDuplicate = set.has(item?.id);
			set.add(item?.id);
			return !isDuplicate;
		});
	}

	function formatPhoneNumber(phoneNumber) {
		const cleaned = ('' + phoneNumber).replace(/\D/g, '');
		const match = cleaned.match(/^(\d{1})(\d{3})(\d{3})(\d{4})$/);
		if (match) {
		  return `+1 (${match[2]}) ${match[3]}-${match[4]}`;
		}
		return phoneNumber;
	  }


	return (
		<>
		 <Head>
			<title>Ottawa Rec Sports - Player</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/images/ORS-Logo.png" />
		</Head>

		{/* Content */}
			<main className="w-full h-screen flex flex-col gap-6 p-5">
				{/* Results */}
				<div className="flex flex-col w-full h-auto bg-white border border-brand-neutral-300 rounded-md">
					<div className="flex justify-between py-3 px-5 border-b border-brand-neutral-300">
						<h1 className="text-lg self-center font-medium">
							{user &&
								user.UserAttributes.find((o) => o.Name === 'name')[
									'Value'
								]}{' '}
							{user &&
								user.UserAttributes.find((o) => o.Name === 'family_name')[
									'Value'
								]}
						</h1>
						<Button
							pill={true}
							className="py-0.5 pr-3 bg-blue-900 hover:bg-blue-800"
							onClick={() => router.back()}
						>
							<IconChevronLeft className="mr-2 h-5 w-5" />
							Back
						</Button>
					</div>

					<div className="grid grid-cols-3 gap-4 p-8">
						{/* Player Avatar */}
						<div className="col-span-3 md:col-span-1 row-span-2 flex flex-col gap-4">
							<img
								src={`${
									profileImage ? profileImage : '/images/defaultProfilePic.jpeg'
								}`}
								className="rounded-full self-center w-[200px] h-[200px] object-cover"
								alt="Player profile image."
							></img>
							<div className="flex justify-center gap-1">
								<Image
									src="/images/medal.png"
									width="26"
									height="26"
									alt="Medal"
								/>
								<Image
									src="/images/medal.png"
									width="26"
									height="26"
									alt="Medal"
								/>
								<Image
									src="/images/medal.png"
									width="26"
									height="26"
									alt="Medal"
								/>
							</div>
						</div>

						{/* Player Information */}
						<div className="col-span-3 md:col-span-2 grid grid-cols-2 gap-y-4 gap-x-8">
							<div className="col-span-1 flex flex-col">
								<h3 className="mb-1 font-light">First Name</h3>
								<div className="py-2 px-3 border rounded-md border-brand-blue-900/25 font-medium">
									{user &&
										user.UserAttributes.find((o) => o.Name === 'name')['Value']}
								</div>
							</div>

							<div className="col-span-1 flex flex-col">
								<h3 className="mb-1 font-light">Last Name</h3>
								<div className="py-2 px-3 border rounded-md border-brand-blue-900/25 font-medium">
									{user &&
										user.UserAttributes.find((o) => o.Name === 'family_name')[
											'Value'
										]}
								</div>
							</div>

							<div className="col-span-1 flex flex-col">
								<h3 className="mb-1 font-light">Location</h3>
								<div className="py-2 px-3 border rounded-md border-brand-blue-900/25 font-medium">
									{user &&
										user.UserAttributes.find(
											(o) => o.Name === 'custom:location'
										)['Value']}
								</div>
							</div>

							<div className="col-span-1 flex flex-col">
								<h3 className="mb-1 font-light">Gender</h3>
								<div className="py-2 px-3 border rounded-md border-brand-blue-900/25 font-medium">
									{user &&
										user.UserAttributes.find((o) => o.Name === 'gender')[
											'Value'
										]}
								</div>
							</div>

							<div className="col-span-1 flex flex-col">
								<h3 className="mb-1 font-light">Email</h3>
								<div className="py-2 px-3 border rounded-md border-brand-blue-900/25 font-medium text-sm">
									{user &&
										user.UserAttributes.find((o) => o.Name === 'email')[
											'Value'
										]}
								</div>
							</div>

							<div className="col-span-1 flex flex-col">
								<h3 className="mb-1 font-light">Phone Number</h3>
								<div className="py-2 px-3 border rounded-md border-brand-blue-900/25 font-medium">
									{user && user.UserAttributes.find((o) => o.Name === 'phone_number') ? (
										<p>{formatPhoneNumber(user.UserAttributes.find((o) => o.Name === 'phone_number')[
											'Value'
										])}</p>
									) : (
										<p>&nbsp;</p>
									)}
								</div>
							</div>
						</div>

						{/* Player Teams */}
						<div className="col-span-3 md:col-span-2 border rounded-md border-brand-blue-900/25">
							<table className="border-collapse table-fixed w-full overflow-hidden rounded-md">
								<thead className="bg-brand-neutral-100 border-b border-brand-blue-900/25">
									<tr className="text-left">
										<th className="py-2 px-3 text-sm font-light w-4/12">
											Sport
										</th>
										<th className="py-2 px-3 text-sm text-center font-light w-4/12">
											Team (s)
										</th>
										<th className="py-2 px-3 text-sm font-light w-4/12">
											Role
										</th>
									</tr>
								</thead>
								<tbody>
								{teams && teams.map((team) => (
										<>
										{team !== null && (
											<tr className="font-light">
												<td className="py-2 px-3 text-[.94rem]">{sport}</td>
												<td className="py-2 text-center">
													<Link className='text-blue-500 underline text-[.92rem]' href={`/teams/${team?.id}`}>{team && team.name}</Link>
												</td>
												<td className="py-2 px-3">
													{team?.player_role === 'Player' && (
														<p className='text-[.92rem]'>Player</p>
													)}
													{team?.player_role === 'Captain' && (
														<p className='text-[.92rem]'>Captain</p>
													)}
												</td>
											</tr>
										)}
										</>
									))}
									{(teams && teams.length === 0) && (
											<>
										<tr className="font-light mx-auto text-center">
											<td className=''></td>
											<td className=''>
												<p>This player is currently in no teams.</p>
											</td>
											<td className=''></td>
										</tr>
										</>
									)}
								</tbody>
							</table>
						</div>

						{/* Player Game History */}
						{/* <div className="col-span-3">
							<h2 className="mb-1 font-light">Games History</h2>

							<div className="col-span-3 border rounded-md border-brand-blue-900/25">
								<table className="border-collapse table-fixed w-full overflow-hidden rounded-md">
									<thead className="bg-brand-neutral-100 border-b border-brand-blue-900/25">
										<tr className="text-left">
											<th className="py-2 px-3 text-sm font-light w-4/12">
												Games Played
											</th>
											<th className="py-2 px-3 text-sm font-light w-4/12">
												Wins
											</th>
											<th className="py-2 px-3 text-sm font-light w-4/12">
												Losses
											</th>
										</tr>
									</thead>
									<tbody>
										<tr className="font-light">
											<td className="py-2 px-3">0</td>
											<td className="py-2 px-3">0</td>
											<td className="py-2 px-3">0</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div> */}
					</div>
				</div>
			</main>
		</>
	);
}
