/**
 * Last updated: 2023-04-11
 *
 * Author(s):
 * Verity Stevens <stev0298@algonquinlive.com>
 * Ghazaldeep Kaur <kaur0762@algonquinlive.com>
 */

import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import SearchBarInput from '@/components/common/SearchBarInput';
import PlayerRow from '@/components/players/PlayerRow';
import AWS from 'aws-sdk';

export default function Players() {
	const [players, setPlayers] = useState([]);
	const [filteredPlayers, filterPlayers] = useState([]);
	var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();

	useEffect(() => {
		fetchUsers();
	}, []);

	// Fetch all users from AWS Cognito:
	const fetchUsers = async () => {
		var params = {
			UserPoolId: 'us-east-1_70GCK7G6t' /* required */,
		};
		cognitoidentityserviceprovider.listUsers(params, function (err, data) {
			if (err) {
				console.log(err, err.stack);
			} else {
				setPlayers(data.Users);
				filterPlayers(data.Users);
			}
		});
	};

	/**
	 * Filter users by first and last name using the search input value.
	 * @param {[Object]} ev Click event
	 */
	function handleSearch(ev) {
		ev.preventDefault();

		let searchValue = document
			.getElementById('player-search')
			.value.toLowerCase();

		let filteredPlayers = players.filter((player) => {
			const firstName = player.Attributes.find((o) => o.Name === 'name')[
				'Value'
			];
			const lastName = player.Attributes.find((o) => o.Name === 'family_name')[
				'Value'
			];

			// Reference: Stack Overflow/zb22 <https://stackoverflow.com/questions/66089303/how-to-filter-full-name-string-properly-in-javascript>
			const arr = searchValue.split(' ');
			return arr.some(
				(el) =>
					firstName.toLowerCase().includes(el) ||
					lastName.toLowerCase().includes(el)
			);
		});

		filterPlayers(filteredPlayers);
	}

	return (
		<>
			<Head>
				<title>Ottawa Rec Sports - Players</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/images/ORS-Logo.png" />
			</Head>

			{/* Content */}
			<main className="w-full h-screen flex flex-col gap-6 p-5">
				{/* Search Bar */}
				<SearchBarInput
					id={'player-search'}
					placeholder={'Search'}
					searchFunction={handleSearch}
				/>
				{/* Results */}
				<div className="flex flex-col w-full h-auto bg-white border border-brand-neutral-300 rounded-md">
					<div className="flex justify-between py-3 px-5 border-b border-brand-neutral-300">
						<h2 className="text-lg self-center">All Players</h2>
					</div>

					<table className="table-auto">
						<thead className="bg-brand-neutral-100">
							<tr className="text-left">
								<th className="py-3 px-5 text-sm font-light w-4/12">Name</th>
								<th className="py-3 text-center text-sm font-light w-2/12">
									Location
								</th>
								<th className="py-3 px-10 text-sm font-light w-2/12 text-center">
									Teams : Roles
								</th>
							</tr>
						</thead>
						<tbody>
							{filteredPlayers &&
								filteredPlayers.map((player, index) => (
								<React.Fragment key={index}>
									<PlayerRow
										key={player.Username}
										player={player}
										index={player.Username}
									/>
									</React.Fragment>
								))}
							<tr>
								<td
									colSpan={6}
									className="pt-8 pb-4 text-center text-sm text-brand-neutral-800"
								>
									End
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</main>
		</>
	);
}
