import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Toast } from 'flowbite-react';
import { IconShieldCheck } from '@tabler/icons-react';
import { useUser } from '@/context/userContext';
// Components
import UserIdentifier from '@/components/common/UserIdentifier';
import SignOutButton from '@/components/common/SignOutButton';

export default function Home() {
	const [user, setUser, authRoles, setAuthRoles] = useUser();
	return (
		<>
			<Head>
				<title>Ottawa Rec Sports</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/images/ORS-Logo.png" />
			</Head>

			<main className={styles.main}>
				<div className='flex flex-col'>
					<UserIdentifier />
					<h1>Home Page</h1>
					<button onClick={() => console.log(user)}>Click Me</button>
					<SignOutButton />
				</div>
			</main>
		</>
	);
}
