/**
 * Last updated: 2023-03-21
 *
 * Author(s):
 * Ghazaldeep Kaur <kaur0762@algonquinlive.com>
 */

import { useState } from 'react';
import Image from 'next/image';
import { IconCameraPlus } from '@tabler/icons-react';
import Head from 'next/head';
import SettingsPage from '@/components/settings-page/SettingPage';
import { useUser } from '@/context/userContext';
import { changeUserAttributes } from '@/utils/graphql.services';

export default function Setting() {
	const [user] = useUser();
	const [userAttributes, setUserAttributes] = useState({});

	const saveAttributes = async () => {
		console.log(userAttributes);
		await changeUserAttributes(userAttributes);
	};
	if (!user) {
		return (
			<>
				<Head>
					<title>Ottawa Rec Sports : Settings</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/images/ORS-Logo.png" />
				</Head>
				<main>
					<div className="flex justify-center">
						<p className="text-xl font-semibold">
							You must be logged in to access this page.
						</p>
					</div>
				</main>
			</>
		);
	} else {
		return (
			<>
				<Head>
					<title>Ottawa Rec Sports : Settings</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/images/ORS-Logo.png" />
				</Head>
				<main>
					<div className="bg-white m-16 p-3 mt-[38rem] sm:mt-20">
						<div className="border-b border-[#c0c0c0] h-[50px] ">
							<p className="font-medium text-base self">My Profile</p>
						</div>
						<div className="flex flex-col overflow-y-scroll">
							<div className="flex justify-center">
								<div className="lg:flex lg:flex-row gap-4 m-5">
									<div>
										<div className="w-[200px] h-[200px] border rounded-full overflow-hidden">
											<Image
												src={'/images/defaultProfilePic.jpeg'}
												alt="profile pic"
												width={200}
												height={200}
												priority
											/>
										</div>
										<IconCameraPlus className="ml-40" />
									</div>
									<SettingsPage setUserAttributes={setUserAttributes} />
								</div>
							</div>
							<div className="flex justify-center">
								<div>
									<button
										className="bg-white h-[30px] w-[90px] rounded-[50px] text-brand-blue-800 font-regular my-4"
										type="button"
									>
										Cancel
									</button>
								</div>
								<div>
									<button
										className="bg-brand-blue-800 h-[30px] w-[90px] rounded-[50px] text-white font-regular my-4"
										type="button"
										onClick={saveAttributes}
									>
										Save
									</button>
								</div>
							</div>
						</div>
					</div>
				</main>
			</>
		);
	}
}
