/**
 * Last updated: 2023-03-10
 *
 * Author(s):
 * Justin Bernard <bern0241@algonquinlive.com>
 */

import React, { useState, useEffect } from 'react';
import Head from 'next/head';
// Components
import SignUpView from '@/components/signup/SignUpView';
import ConfirmSignUpView from '@/components/signup/ConfirmSignUpView';

export default function Signup() {
	const [uiState, setUiState] = useState(null);
	const [email, setEmail] = useState(''); // Email that gets passed between UI states/screens
	const [confirmationCode, setConfirmationCode] = useState('');
	useEffect(() => {
		setUiState('signUp');
	}, []);

	return (
		<>
			<Head>
				<title>Ottawa Rec Sports : Signup</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/images/ORS-Logo.png" />
			</Head>

			{/* UI STATES (displaying components individually) */}
			{uiState === 'signUp' && (
				<SignUpView email={email} setEmail={setEmail} setUiState={setUiState} />
			)}
			{uiState === 'confirmSignUp' && (
				<ConfirmSignUpView
					email={email}
					setUiState={setUiState}
					confirmationCode={confirmationCode}
					setConfirmationCode={setConfirmationCode}
				/>
			)}
		</>
	);
}
