/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://oaffrlnuhjd3rd6wuzaxcjesqa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-72bu5tnr7jdqddrvihzgtlknca",
    "aws_cognito_identity_pool_id": "us-east-1:26637e05-8fc9-4146-85ca-e72861082683",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4qFJvD5yd",
    "aws_user_pools_web_client_id": "2d0st5d5056i5bul2la1drdr1n",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "orsapp85f2c7cbe0574cb686d19e96d2fe5a1d183134-myenvtwo",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
